'use client';
//import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './navbar';
import React, { useState } from 'react';

const MainComponent = () => {
  const [userEmail, setUserEmail] = useState('user@example.com');

  const handleLogout = () => {
    // Implement your logout logic here
    console.log('User logged out');
  };

  const handleLogin = () => {
    // Implement your login logic here
    console.log('User logged in');
  };

  return (
    <Navbar email={userEmail} onLogout={handleLogout} />
    // You can include the rest of the MainComponent content here
  );
};

const inter = Inter({ subsets: ['latin'] })

/*export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/
export default function RootLayout({
  children,
}: {


  
  children: React.ReactNode
}

)

{
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <MainComponent></MainComponent>
        {children}</body>
    </html>
  )
}
